//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modules.Channel.B2B.DAL.ChannelCatalog
{
    using System;
    using System.Collections.Generic;
    
    public partial class b2b_identities
    {
        public System.Guid Identity_ID { get; set; }
        public int Profile_ID { get; set; }
        public string Customer_ID { get; set; }
        public string Username { get; set; }
        public string Credential { get; set; }
        public string CredentialMac { get; set; }
        public string Group_guid { get; set; }
        public bool Enabled { get; set; }
        public string LastActivityDate { get; set; }
        public string LastPasswordChangedDate { get; set; }
        public string CreationDate { get; set; }
        public bool IsLockedOut { get; set; }
        public string LastLockedOutDate { get; set; }
        public Nullable<int> FailedPasswordAttemptCount { get; set; }
        public string FailedPasswordAttemptWindowStart { get; set; }
        public Nullable<bool> IsTestAccount { get; set; }
        public string Encrypted_Credential { get; set; }
        public bool IsCredentialComplexityRelaxed { get; set; }
        public string Relax_Credential_Comment { get; set; }
        public Nullable<bool> isMigrated { get; set; }
    
        public virtual b2b_profile b2b_profile { get; set; }
    }
}
