//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modules.Channel.B2B.DAL.ChannelCatalog
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class b2b_logEntities : DbContext
    {
        public b2b_logEntities()
            : base("name=b2b_logEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<b2b_identities> b2b_identities { get; set; }
        public virtual DbSet<b2b_profile> b2b_profile { get; set; }
        public virtual DbSet<Catalog_Scheduler> Catalog_Scheduler { get; set; }
    }
}
