//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modules.Channel.B2B.DAL.ChannelCatalog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catalog_Scheduler
    {
        public long Schedule_ID { get; set; }
        public System.Guid Identity_ID { get; set; }
        public string Catalog_Type { get; set; }
        public Nullable<System.DateTime> Start_Date { get; set; }
        public Nullable<System.DateTime> End_Date { get; set; }
        public Nullable<int> Frequency { get; set; }
        public Nullable<System.TimeSpan> Time_Of_Send { get; set; }
        public Nullable<System.DateTime> Last_Publish_Time { get; set; }
        public Nullable<System.DateTime> Next_Publish_Time { get; set; }
        public bool IsScheduled { get; set; }
        public Nullable<int> Frequency_Type { get; set; }
    }
}
