//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modules.Channel.B2B.DAL.ChannelCatalog
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogMaster_Auto
    {
        public long CatalogId { get; set; }
        public string CatalogName { get; set; }
        public string User_Name { get; set; }
        public Nullable<System.Guid> AccessGroup { get; set; }
        public long ProfileId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ValidityStartDate { get; set; }
        public System.DateTime ValidityEndDate { get; set; }
        public Nullable<short> CatalogFormatTypeId { get; set; }
        public Nullable<int> CatalogStatusId { get; set; }
        public Nullable<bool> IsStandardConfig { get; set; }
        public Nullable<bool> IsUpDnSaleEnabled { get; set; }
        public Nullable<bool> IsSNPEnabled { get; set; }
        public Nullable<bool> IsAbsolutePriceEnabled { get; set; }
        public Nullable<bool> IsDefaultOptionEnabled { get; set; }
        public Nullable<bool> IsOptionTypeEnabled { get; set; }
        public Nullable<bool> IsFinalPriceEnabled { get; set; }
        public Nullable<bool> IsSkuDetailsEnabled { get; set; }
        public Nullable<int> ThreadId { get; set; }
        public string GPShipToCountry { get; set; }
        public string GPShipToCurrency { get; set; }
        public Nullable<bool> isGlobalPortal { get; set; }
        public string ExternalMailingAddresses { get; set; }
        public string CatalogHeaderXml { get; set; }
        public string AppRegion { get; set; }
        public string Catalog_Type { get; set; }
        public Nullable<long> ParentCatalogId { get; set; }
        public Nullable<bool> IsCatalogPublished { get; set; }
        public string InternalMailingAddresses { get; set; }
        public Nullable<System.Guid> IdentityId { get; set; }
        public string CustomerId { get; set; }
        public string ProfileName { get; set; }
        public Nullable<bool> IsSystem { get; set; }
    }
}
