//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modules.Channel.B2B.DAL.ChannelCatalog
{
    using System;
    using System.Collections.Generic;
    
    public partial class Channel_Catalog_PackagingData
    {
        public string OrderCode { get; set; }
        public string LOB { get; set; }
        public string ConfigName { get; set; }
        public Nullable<int> ShipWeight { get; set; }
        public Nullable<int> PackageLength { get; set; }
        public Nullable<int> PackageWidth { get; set; }
        public Nullable<int> PackageHeight { get; set; }
        public Nullable<int> PalletLength { get; set; }
        public Nullable<int> PalletWidth { get; set; }
        public Nullable<int> PalletHeight { get; set; }
        public Nullable<int> PalletUnitsPerLayer { get; set; }
        public Nullable<int> PalletLayerPerPallet { get; set; }
        public Nullable<int> PalletUnitsPerPallet { get; set; }
    }
}
