//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modules.Channel.B2B.DAL.Inventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class b2b_profile
    {
        public int id { get; set; }
        public string user_id { get; set; }
        public string password { get; set; }
        public string description { get; set; }
        public string customer_id { get; set; }
        public Nullable<System.DateTime> last_mod_date { get; set; }
        public string dell_cust_id { get; set; }
        public string name_format_type { get; set; }
        public string buyer_part_no { get; set; }
        public int Template_ID { get; set; }
        public bool test_Account { get; set; }
        public bool b2b_active { get; set; }
        public bool line_item_details { get; set; }
        public string dbn { get; set; }
        public int unspsc_length { get; set; }
        public string CIW { get; set; }
        public int OCI_Sku_Placement_Id { get; set; }
        public string currency_code { get; set; }
        public bool allow_adhoc_order { get; set; }
        public string CIWSupportEmail { get; set; }
        public bool Show_2nd_credential { get; set; }
        public bool Include_UNSPSC { get; set; }
        public bool Include_Long_description { get; set; }
        public bool Include_Manufact_Part_Number { get; set; }
        public bool Include_Manufact_Part_Name { get; set; }
        public string vendor_id { get; set; }
        public string contract_code { get; set; }
        public string cust_field1 { get; set; }
        public string cust_field2 { get; set; }
        public string cust_field3 { get; set; }
        public string cust_field4 { get; set; }
        public string cust_field5 { get; set; }
        public bool negotiate_shipping { get; set; }
        public bool ShipTo_Validate_Address { get; set; }
        public bool BillTo_Validate_Address { get; set; }
        public string POR_URL { get; set; }
        public string CC_ExpirationDate { get; set; }
        public string CC_Holder_Name { get; set; }
        public bool no_lease_item_entries { get; set; }
        public int basket_reuse_interval { get; set; }
        public string group_guid { get; set; }
        public string create_by { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public string modify_by { get; set; }
        public Nullable<System.DateTime> modify_date { get; set; }
        public int POResponseType { get; set; }
        public bool Prepend_SKU { get; set; }
        public bool Canada_Validate_Address { get; set; }
        public string PO_Fail_Ext_Email { get; set; }
        public string POR_UserName { get; set; }
        public string POR_Password { get; set; }
        public Nullable<int> Product_Lead_Time { get; set; }
        public int Sequence_ID_Format { get; set; }
        public bool Include_LineItem_LongText { get; set; }
        public bool Include_LineItem_ContractCode { get; set; }
        public bool SuccessCode_DuplicatePO { get; set; }
        public string cc_number_encrypted { get; set; }
        public string Encrypted_Password { get; set; }
        public bool Enable_BuyerCatalog { get; set; }
        public string Auth_DynamicSettings { get; set; }
        public string OR_DynamicSettings { get; set; }
        public string PO_DynamicSettings { get; set; }
        public string BC_DynamicSettings { get; set; }
        public bool ASN_Enabled { get; set; }
        public string ASN_DynamicSettings { get; set; }
        public bool POC_Enabled { get; set; }
        public string POC_DynamicSettings { get; set; }
        public bool IsRetailCustomer { get; set; }
        public string OR_UNSPSC_VersionID { get; set; }
        public Nullable<int> GracePeriod { get; set; }
        public Nullable<int> CatalogFormatTypeId { get; set; }
        public Nullable<bool> IsStdConfigEnabled { get; set; }
        public Nullable<bool> IsStdConfigUpSellDownSellEnabled { get; set; }
        public Nullable<bool> IsSNPEnabled { get; set; }
        public Nullable<bool> IsShowAbsPriceEnabled { get; set; }
        public Nullable<bool> IsIncludeDefaultOptionsEnabled { get; set; }
        public Nullable<bool> IsOptionTypeEnabled { get; set; }
        public Nullable<bool> IsShowFinPriceEnabled { get; set; }
        public Nullable<bool> IsSkuDetailEnabled { get; set; }
        public Nullable<bool> IsASAPCustomer { get; set; }
        public bool ASN_ChannelEnabled { get; set; }
        public Nullable<int> ASN_DeliveryPreference_Id { get; set; }
        public bool ASN_ChannelCancelEnabled { get; set; }
    }
}
